#!/usr/bin/env node

module.exports = function(d) {
    if (this.ids[d.method] === undefined) this.ids[d.method] = 0;
    if (this.setIdImmediate) clearImmediate(this.setIdImmediate);
    this.setIdImmediate = setImmediate(async () => {
        console.log(`setting id ${d.method} to ${this.ids[d.method]}`);
        this.db.run(
            `update ids
            set count = ${this.ids[d.method]}
            where name = "${d.method}"`
        );
    });
    return this.ids[d.method]++;
};
