#!/usr/bin/env node

module.exports = function() {
    for (let table of require("tables")) {
        this.db.serialize(() => {
            if (table.reset)
                this.db.run(
                    `drop table
                    if exists
                    ${table.name}`
                );
            this.db.run(
                `create table
                if not exists
                ${table.name} (${table.def})`
            );
        });
    };
};
