#!/usr/bin/env node

async function handler(d) {

    let respond = e => this.end(JSON.stringify(e));
    let error = e => respond({ error: e });

    try {
        d = JSON.parse(d.toString().match(/(\S+)$/)[0]);
        respond(await require("getresponse")(d));
    } catch (e) {
        error(e.toString());
        throw e;
    }

};

module.exports = function(socket) {
    socket.on("data",
        handler.bind(socket)
    );
};
