#!/usr/bin/env node

async function handler(d) {
    let respond = e => this.socket.end(JSON.stringify(e));
    try {
        d = JSON.parse(d.toString().match(/(\S+)$/)[0]);
        let response = await require("getresponse")(d);
        require("updatedb").bind(this.db)(d, response);
        respond(response);
    } catch (e) {
        respond({ error: e })
        console.log({ error: e });
        return;
    }
};

module.exports = function(socket) {
    socket.on("data", handler.bind({ db: this, socket: socket }));
};
