#!/usr/bin/env node

module.exports = [
	{
		"anonymous": false,
		"inputs": [
			{
				"indexed": false,
				"internalType": "uint64",
				"name": "id",
				"type": "uint64"
			},
			{
				"indexed": false,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "Pay",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "uint64",
				"name": "id",
				"type": "uint64"
			}
		],
		"name": "pay",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	}
];
