#!/usr/bin/env node

let xdex = {
    db: new (require("sqlite3")).Database("xdex.db"),
    ids: {
        addLiquidity: null
    }
};

require("initdb").bind(xdex)();

(async () => {
    let ids = Object.keys(xdex.ids);
    await Promise.all(ids.map(require("initid").bind(xdex)));
    require("net").Server(require("listener").bind(xdex)).listen(80);
})();
