#!/bin/bash

echo '{"config":{"chainId":CHAIN,"homesteadBlock":0,"eip150Block":0,"eip155Block":0,"eip158Block":0,"byzantiumBlock":0,"constantinopleBlock":0,"petersburgBlock":0,"ethash":{}},"difficulty":"1","gasLimit":"8000000","alloc":{"ADDRESS":{"balance":"100000000000000000000000"}}}' | \
    sed "s/ADDRESS/$address/g" | \
    sed "s/CHAIN/8000/" > \
    tmp/genesis.json
