#!/usr/bin/env node

module.exports = async function(req) {
    let res = {};
    await Promise.all([
        this.getId(req, res)
    ]);
    console.log(res);
    /*let [
        response.id
    ] = await Promise.all([
        this.getId(req)
    ]);
    console.log(`response ${response}`);
    /*let response = {};
    response.id = ;
    response.payInfo = this.getPayInfo(req);
    await Promise.all(response.id, response.payInfo);
    res.writeHead(
        200,
        { "Content-Type": "text/plain" }
    );
    res.write(JSON.stringify(response));
    res.end();*/
};
