#!/usr/bin/env node

let sqlite3 = require("sqlite3");
let tables = require("tables");

module.exports = {
    startDatabase: function() {
        this.db = new sqlite3.Database("xdex.db");
        for (let table of tables) {
            this.db.serialize(() => {
                if (table.reset)
                    this.db.run(
                        `drop table
                        if exists
                        ${table.name}`
                    );
                this.db.run(
                    `create table
                    if not exists
                    ${table.name} (${table.def})`
                );
                if (table.name == "ids") {
                    let ids = [
                        "addLiquidity"
                    ];
                    ids.forEach(id => {
                        this.db.run(
                            `insert or ignore into ids
                            (name, count) values
                            ("${id}", 0)`
                        );
                    });
                }
            });
        };
        this.dbStarted = true;
        if (this.serverStarted && this.dbStarted)
            this.on("req", require("isvalidreq"));
    }
};
